"""
Django's settings for star project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# загружаем данные для сессии
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = C:\Users\dyako\PycharmProjects\Programming\2Course\star\star
# базовый путь к проекту (в котором лежит manage.py)
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Меняется на False, когда выкатывается на основной сервер
# (чтобы пользователю не отображалась отладочная информация на странице)
DEBUG = eval(os.getenv('DEBUG'))

# * - указывает, что приложение может работать на любых хостах
# или можно указать свои, например, mysite.com
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS').split(',' or ', ')

# Здесь определяем наши приложения (отдельные логические блоки, которые нам необходимы для проекта)

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # приложение для дополнительной отладки django
    'debug_toolbar',

    # наши приложения:
    # главная и статичные страницы
    'main',
    # документы и заявления
    'docs',
    # вакансии
    'vacancies',
]

# Промежуточное ПО, которое отвечает за безопасность, сессии (автоматическую обработку cookies-файлов на ПК юзеров)...
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # добавляем дополнительный инструмент для отладки
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

# файл urls.py, где указаны все url-адреса нашего приложения
ROOT_URLCONF = 'star.urls'

# шаблонизатор для отрисовки html-страниц
# DIRS - где дополнительно искать шаблоны
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# какой протокол работы используем (wsgi or asgi)
WSGI_APPLICATION = 'star.wsgi.application'

# подключение БД
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# валидаторы паролей (минимальная длина, верхний и нижний регистр и тд)
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# на каком языке работает приложение django, на каком языке будет отображаться admin-панель,
# оповещения для пользователей и тд
LANGUAGE_CODE = 'ru-ru'

# в какой временной полосе работает приложение
TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# какой префикс будет добавлен, при получении статических файлов (css, js и тд), в браузере будет отображаться
# следующий примерный путь: /static/deps/css/style.css
STATIC_URL = 'static/'
if DEBUG:
    # указываем дополнительные места, где django нужно искать статику
    # бросаем папку static в корень проекта, так как будем использовать одинаковые зависимости для всех приложений
    STATICFILES_DIRS = [
        BASE_DIR / 'static'
    ]
else:
    STATIC_ROOT = BASE_DIR / 'static'

# какой префикс будет добавлен, при получении медиа-файлов
MEDIA_URL = 'media/'

# где django будет искать медиа-файлы (в папке media)
MEDIA_ROOT = BASE_DIR / 'media'

# где будет работать дополнительный инструмент для отладки
INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

# автоинкремент (+1) id для каждой новой записи в БД в каждом приложении
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
# как отправляются сообщения (протоколы)
EMAIL_USE_TLS = eval(os.getenv('EMAIL_USE_TLS'))
EMAIL_USE_SSL = eval(os.getenv('EMAIL_USE_SSL'))
# порт почты
EMAIL_PORT = int(os.getenv('EMAIL_PORT'))
# почта, с которой будут отправляться сообщения
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
