# Generated by Django 5.0.6 on 2024-06-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название заявления')),
                ('file_app', models.FileField(upload_to='documents/applications/', verbose_name='Заявление')),
            ],
            options={
                'verbose_name': 'Заявление',
                'verbose_name_plural': 'Заявления',
                'db_table': 'applications',
            },
        ),
    ]
