# Generated by Django 5.0.6 on 2024-06-17 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_one', models.TextField(max_length=700, verbose_name='Первый абзац')),
                ('paragraph_two', models.TextField(max_length=500, verbose_name='Второй абзац')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Историю компании',
                'verbose_name_plural': 'История компании',
                'db_table': 'history_company',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1300, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Полезную информацию',
                'verbose_name_plural': 'Полезная информация',
                'db_table': 'info',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Заголовок новости')),
                ('text', models.TextField(max_length=1300, verbose_name='Текст новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1300, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Политику конфиденциальности',
                'verbose_name_plural': 'Политика конфиденциальности',
                'db_table': 'policy',
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1300, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Кадровый резерв',
                'verbose_name_plural': 'Кадровый резерв',
                'db_table': 'reserve',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('job_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Должность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доп. информация',
                'verbose_name_plural': 'Доп. информация',
            },
        ),
    ]
