# Generated by Django 5.0.6 on 2024-06-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_historycompany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historycompany',
            options={'verbose_name': 'Историю компании', 'verbose_name_plural': 'История компании'},
        ),
        migrations.AddField(
            model_name='historycompany',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео'),
        ),
    ]
