# Generated by Django 5.0.6 on 2024-06-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_historycompany_options_historycompany_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1300, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Кадровый резерв',
                'verbose_name_plural': 'Кадровый резерв',
                'db_table': 'reserve',
            },
        ),
    ]
