# Generated by Django 5.0.6 on 2024-06-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1300, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Политику конфиденциальности',
                'verbose_name_plural': 'Политика конфиденциальности',
                'db_table': 'policy',
            },
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Полезную информацию', 'verbose_name_plural': 'Полезная информация'},
        ),
    ]
