# Generated by Django 5.0.6 on 2024-06-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Доп. информация', 'verbose_name_plural': 'Доп. информация'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Должность'),
        ),
    ]
