# Generated by Django 5.0.6 on 2024-06-17 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilesVacanciesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_file_title', models.CharField(max_length=70, verbose_name='Название раздела файлов')),
            ],
            options={
                'verbose_name': 'Раздел файлов',
                'verbose_name_plural': 'Разделы с файлами',
                'db_table': 'files_vacancies_group',
            },
        ),
        migrations.CreateModel(
            name='VacanciesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=70, verbose_name='Название раздела')),
            ],
            options={
                'verbose_name': 'Раздел вакансий',
                'verbose_name_plural': 'Разделы вакансий',
                'db_table': 'vacancies_group',
            },
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200, verbose_name='Название должности')),
                ('subunit', models.CharField(blank=True, max_length=70, null=True, verbose_name='Название подразделения')),
                ('required_education', models.CharField(blank=True, max_length=200, null=True, verbose_name='Требуемое образование')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('salary', models.CharField(blank=True, max_length=6, null=True, verbose_name='Зарплата')),
                ('vacancies_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.vacanciesgroup', verbose_name='Раздел вакансий')),
            ],
            options={
                'verbose_name': 'Вакансию',
                'verbose_name_plural': 'Вакансии',
                'db_table': 'vacancies',
            },
        ),
        migrations.CreateModel(
            name='VacFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название файла')),
                ('file_vac', models.FileField(blank=True, null=True, upload_to='documents/vacancies/', verbose_name='Файл для раздела вакансий')),
                ('vac_files_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vac_files', to='vacancies.filesvacanciesgroup', verbose_name='Раздел файлов вакансий')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'db_table': 'vac_files',
            },
        ),
    ]
