# Generated by Django 5.0.6 on 2024-06-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacfiles',
            name='file_name',
        ),
    ]
